# Site settings
title: Susan Walker
description: 'Projects'
url: 'http://susanwalker.github.io'
baseurl: ''
profilepic: 'images/main.jpg'
bkimage: ''
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Susan Walker'
  email: susanwalker8@gmail.com
  github_username:  susanwalker
  # linkedin_username:  

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
